repos:
  - repo: local
    hooks:
      - id: notebook-clear-output
        name: notebook-clear-output
        files: \.ipynb
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
